Repository witseie-elen4010/2022-group-lab-005, pull requests merged in 2022-06, with the labels that each got.

#64 Backend game logic
  src/public/game.css
  src/public/game.js
  src/services/socket.cjs
  src/views/game.html
Labels: developer-sized-story

#69 Starting to finalise layout and fixed virtual keyboard
  src/public/game.css
  src/public/game.js
  src/views/game.html
Labels: enhancement

#70 Updated player and opponent layouts and styling, need to change: play…
  src/public/game.css
  src/public/game.js
  src/views/game.html
Labels: enhancement, developer-sized-story

#71 Lobby backend work
  package-lock.json
  package.json
  src/public/game.js
  src/public/lobby.js
  src/routes/gameRoutes.cjs
  src/services/socket.cjs
  src/views/lobby.html
Labels: developer-sized-story

#73 Custom word
  src/public/lobby.js
  src/routes/lobbyRoutes.cjs
  src/services/lobby.cjs
  src/views/lobby.html
Labels: user-story

#75 Made some minor changes to the UI so that bootstrap components are used
  package-lock.json
  package.json
  src/public/game.js
  src/public/lobby.js
  src/views/lobby.html
Labels: enhancement

#76 Settings
  src/public/darkmode.css
  src/public/fetchMode.js
  src/public/setMode.js
  src/public/settings.cjs
  src/routes/userRoutes.cjs
  src/services/settings_db.cjs
  src/views/home.html
  src/views/settings.html
Labels: user-story

#77 Game database
  package-lock.json
  package.json
  src/public/game.js
  src/public/lobby.js
  src/services/lobby.cjs
  src/services/socket.cjs
  src/views/lobby.html
Labels: developer-sized-story

#87 Lobby layout improvement
  src/views/game.html
  src/views/lobby.html
Labels: enhancement

#88 Fixed the game page so that it works with the new db layout.
  src/public/game.js
  src/public/utils.js
  src/services/lobby.cjs
  src/services/socket.cjs
  src/views/game.html
Labels: bug

#91 Fixed virtual keyboard bug
  src/public/game.css
  src/public/game.js
  src/public/generalStats.cjs
  src/services/socket.cjs
  src/views/game.html
  src/views/lobby.html
Labels: bug

#93 Notification on game end
  src/public/game.js
  src/public/lobby.js
  src/views/game.html
Labels: user-story

#95 Settings username update
  src/public/fetchMode.js
  src/public/sendToServer.cjs
  src/public/setMode.js
  src/routes/userRoutes.cjs
  src/services/settings_db.cjs
  src/views/home.html
  src/views/settings.html
Labels: developer-sized-story

#96 Word guess history timestamp bug fix
  src/services/lobby.cjs
  src/services/socket.cjs
Labels: bug

#99 Improved the UI standardisation of the home page
  src/public/game.css
  src/public/game.js
  src/views/game.html
  src/views/home.html
  src/views/lobby.html
Labels: enhancement

#102 Join game and create game buttons disabled
  src/public/lobby.js
Labels: enhancement

#103 Fixed word logging slowing down the game.
  src/services/socket.cjs
Labels: bug

#104 Dark Mode Saved in and Loaded from Cookies
  src/public/fetchMode.js
  src/public/login.cjs
  src/public/setMode.js
  src/public/settings.cjs
  src/views/Login.html
  src/views/home.html
  src/views/settings.html
Labels: enhancement

#106 Responsiveness + mobile view
  src/public/game.css
  src/views/404.html
  src/views/Login.html
  src/views/Statistics.html
  src/views/about.html
  src/views/changeBackground.html
  src/views/form.html
  src/views/friends.html
  src/views/game.html
  src/views/home.html
  src/views/lobby.html
  src/views/matchHistory.html
  src/views/settings.html
  src/views/test.html
Labels: enhancement

#107 Bug fix: added a new minimum players of 3 for custom games
  package-lock.json
  package.json
  src/public/lobby.js
Labels: enhancement

#112 User joins game they are already in
  src/public/game.js
  src/services/socket.cjs
Labels: enhancement

#115 Game type now in sessionStorage.
  src/public/lobby.js
  src/services/socket.cjs
Labels: enhancement

#117 Custom game UI
  src/public/game.css
  src/public/game.js
  src/public/lobby.js
Labels: user-story

#123 Validate words + nobody wins
  src/public/game.js
  src/public/lobby.js
  src/services/lobby.cjs
  src/services/socket.cjs
Labels: enhancement, user-story

#126 UI standardisation
  src/public/friends.cjs
  src/public/lobby.js
  src/public/setMode.js
  src/views/friends.html
  src/views/home.html
  src/views/lobby.html
  src/views/settings.html
  src/views/statistics.html
Labels: enhancement

#132 Last letter bug should be fixed BUT NOTE THE "Word contains invalid characters" bug!
  src/public/game.js
Labels: bug, help wanted, user-story

#133 "Word contains invalid characters" bug fix
  src/services/lobby.cjs
Labels: bug

#146 Bug fixes for the lobby and custom game
  src/public/lobby.js
  src/services/socket.cjs
Labels: bug

#148 Custom Word Field in Dark Mode
  src/public/lobby.js
Labels: bug
