Repository witseie-elen4010/2022-group-lab-005, pull requests merged in 2022-05, with the labels that each got.

#12 Word log
  .github/workflows/main_hazardaguess.yml
  index.js
  mainRoutes.js
  package-lock.json
  package.json
  public/guessWord.js
  services/poolManagement.js
  services/wordQuery.js
  tests/wordQuery.test.js
  views/test.html
Labels: developer-sized-story

#13 Game settings
  __tests__/routing.test.js
  index.html
  index.js
  mainRoutes.js
  package-lock.json
  package.json
  public/fetchMode.js
  public/sendToServer.js
  public/settings.js
  services/poolManagement.js
  services/testDB.js
  views/settings.html
Labels: developer-sized-story

#17 Start screen
  index.js
  mainRoutes.js
  package.json
  services/lobby.js
  services/poolManagement.js
  services/testDB.js
  testing/lobby.test.js
  views/about.html
  views/form.html
  views/game.html
  views/home.html
  views/lobby.html
Labels: user-story

#31 Small changes to login screen UI and backend.
  src/mainRoutes.js
  src/public/login.js
  src/public/loginAssets.css
  src/services/login_db.js
  src/views/Login.html
Labels: enhancement

#32 Multiplayer communication.
  src/index.js
  src/public/lobby.js
  src/routes/lobbyRoutes.js
  src/services/soc.js
  src/views/lobby.html
Labels: user-story

#33 Login screen Redirect and background and implemented account register
  src/mainRoutes.js
  src/public/Background.jpg
  src/public/Background.png
  src/public/login.js
  src/public/loginAssets.css
  src/services/login_db.js
  src/views/Login.html
Labels: enhancement

#35 Adding support for sockets.
  index.js
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
  src/routes/lobbyRoutes.js
  src/views/lobby.html
Labels: developer-sized-story

#37 Added basics to begin the game board
  src/public/game.css
  src/public/game.js
  src/views/game.html
Labels: user-story

#38 Game communication
  index.js
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
  src/public/lobby.js
  src/routes/lobbyRoutes.js
  src/services/soc.js
  src/views/lobby.html
Labels: developer-sized-story

#39 game logic implemented with dummy word variable
  src/public/game.css
  src/public/game.js
Labels: user-story

#52 Game communication
  src/public/game.js
  src/services/socket.cjs
Labels: user-story
